import type { Metadata } from "next";
import { Geist, Geist_Mono ,Inter } from "next/font/google";
import "./globals.css";



const inter = Inter({
  subsets: ['latin'], 
  variable: '--font-inter',
  weight: ['400', '500', '700'], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" crxlauncher="">
      <body
        className={`${inter.variable} antialiased` }
      >
        {children}
      </body>
    </html>
  );
}
